This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file /Users/martin/Documents/GitHub/FYP-report/.texpadtmp/PhDThesis_example.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/martin/Documents/GitHub/FYP-report/.texpadtmp/PhDThesis_example.acn...done (0 entries accepted, 0 rejected).
Nothing written in /Users/martin/Documents/GitHub/FYP-report/.texpadtmp/PhDThesis_example.acr.
Transcript written in /Users/martin/Documents/GitHub/FYP-report/.texpadtmp/PhDThesis_example.alg.
